### ISSUE TITLE
1 Liner Sorting

### ISSUE THREAD

**Issue by warmachine028** [Himanshu44626748/Algorithm#34]
Hi! I would like to add 1 Liner quick sort in python . Could you assign me this Issue with hactoberfest2021 label so that I can make a pull request

**Comment by kathan3** [comment]
Hi!Could your assign this issue to me?

**Comment by warmachine028** [comment]
Hi !, I've already added a one liner sorting algorithm in python in #58 .Could you merge my PR :)

> Hi!Could your assign this issue to me?
@kathan3 you can explore any other one liners in python , there are plenty of them around trust me :)
